# Generated by Django 5.2.2 on 2025-07-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_master_services_order_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='services',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтвержденная'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Время выполнения в минутах', verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная услуга'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
