# Generated by Django 5.2.2 on 2025-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_master_services_remove_order_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(default=None, related_name='masters', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(default=None, related_name='orders', to='core.service', verbose_name='Услуги'),
        ),
    ]
