# Generated by Django 5.2.2 on 2025-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_appointment_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('ai_moderating', 'На модерации'), ('ai_approved', 'Одобрен ИИ'), ('ai_rejected', 'Отклонен ИИ'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
