# Generated by Django 5.2.2 on 2025-08-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=5, verbose_name='Рейтинг'),
        ),
    ]
